### ISSUE TITLE
Invitation to client

### ISSUE THREAD

**Issue by Bony5690** [SolveSmartCities/SolveSmartCities.App#136]
While Logged in as a service provider on localhost44352 I sent an invite to a client to create a profile and then it redirected me to client overview. I did not receive any email notification.

**Comment by reidcompton** [comment]
The emails don't work on localhost at this time. Email-related features have to be tested on staging unfortunately. 

The workaround for adding a member locally is to use this URL:
https://localhost:44352/member/createprofile?id={memberId}

with {memberId} being the Id of the member you just created, which you could access by running `SELECT * FROM Members ORDER BY Id DESC` and the first one should be your most recently added.
