### ISSUE TITLE
Security protocol for users, clients(job candidates), and solve team 

### ISSUE THREAD

**Issue by mattweevu** [SolveSmartCities/SolveSmartCities.App#159]
With Matt Erickson help we will need a security protocol for three different types of people?

1) service providers
2) Job candidates
3) solve team

I imagine a two step log-in? and more that Matt erickson knows about.

**Comment by reidcompton** [comment]
We have role based security for the 3 users mentioned above, and two-factor authentication is logged in ticket #94. Closing as duplicate.
