### ISSUE TITLE
Rank skill sets from 1 to 10 (10 is most challenging)

### ISSUE THREAD

**Issue by mattweevu** [SolveSmartCities/SolveSmartCities.App#162]
This may become valuable one day so people know skills based on salaries. Plus it helps companies find that person easier. This was Hal idea..

**Comment by reidcompton** [comment]
We already do this, with low/medium/high skill ratings. Do we need 1-10 instead?


--
Reid Compton

727.244.7420
reid@reidcompton.com
reidcompton.com
