### ISSUE TITLE
Create Button "Add Case Notes" Under - View Profile or Edit Profile

### ISSUE THREAD

**Issue by mattweevu** [SolveSmartCities/SolveSmartCities.App#85]
Pressing Add Case Notes will allow the case manager to take notes on their client. Case notes seems to be "broad" term so an MVP of "case notes" might include: 
- Automatic Date / Time Grab 
- Case Manager Name Writing Notes
- Text Field to take Notes / Submit button

**Comment by reidcompton** [comment]
@mattweevu -- As discussed, case notes currently exist for the Case Manager user. Here is the menu view, and the "add note" view.
When a note is added in the database, we are currently tracking
- Member
- Case Manager
- Created Date
- Note
- Outcome
- Outcome Weight

The last tie into the concept of "Outcomes" that I have laid the foundation for but have not yet fully fleshed out, but the basic idea would be that we could eventually have notes tie into certain goals and progressively move a member towards completion.

![screen shot 2017-06-05 at 7 15 56 pm](https://cloud.githubusercontent.com/assets/3121908/26808704/6732cf4e-4a24-11e7-8c14-447c57853ec9.JPG)
![screen shot 2017-06-05 at 7 16 45 pm](https://cloud.githubusercontent.com/assets/3121908/26808703/6730532c-4a24-11e7-9a88-4bc1dc20135f.JPG)
